import Head from 'next/head';
import { createContext, useState } from 'react';
import Header from '../components/Headers';
import Layout from '../components/layout';
import '../styles/globals.css';

export const GlobalContext = createContext({});
function MyApp({ Component, pageProps }) {
  const [show, setShow] = useState(false);
  const value = { show, setShow };
  return (
    <>
      <Head>
        <title>Add to cart</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GlobalContext.Provider value={value}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </GlobalContext.Provider>
    </>
  );
}

export default MyApp;
